name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # Match the Python version specified in pyproject.toml

      # Install PDM
      - name: Install PDM
        run: python -m pip install --upgrade pip pdm

      # Install dependencies using PDM
      - name: Install dependencies
        run: pdm install --dev

      # Run tests
      - name: Run tests
        run: pdm run pytest